base_url = "https://a-gavin.github.io"
build_search_index = false

[markdown]
highlight_code = true

[extra]
favicon = "favicon.ico"

# The profile on home page
[extra.profile]
professional_interests = [
    "Computer Networks and Wireless Systems",
    "Systems Software Development",
]
about_me_paragraphs = [
    "Hi there, I'm Alex [he/they]. I love working with computers and am passionate about open source!",
    "I currently work at the intersection of computer networking and software engineering, contributing to and supporting a Linux-based wireless and network testing platform.",
]
name = "Alex Gavin"
position = "Software Engineer, Candela Technologies"
avatar_url = "images/avatar.jpg"
